#!/bin/sh

# This is configure script that will prepare this project for build on android

ANDROID_SDK=/opt/android-sdk
ANDROID_NDK=/opt/android-ndk
export ANDROID_SDK
export ANDROID_NDK

if [ ! -d release ]
then
    mkdir release
fi

q=x
if [ "$#" -gt 0 ];
then
    q="$1"
else
    echo "Specify absolute path to Qt installation"
    read q
fi

cd release
cmake ../HuggleLite -DCMAKE_PREFIX_PATH="$q" -DCMAKE_TOOLCHAIN_FILE=../../deps/qt-android-cmake/toolchain/android.toolchain.cmake
