#!/bin/sh

# This is configure script that will prepare this project for build on android

ANDROID_SDK=/opt/android-sdk
ANDROID_NDK=/opt/android-ndk
export ANDROID_SDK
export ANDROID_NDK
TOOLCHAIN=/opt/android-toolchain

if [ ! -d "$ANDROID_SDK" ];then
    echo "Android SDK not found in $ANDROID_SDK"
    exit 1
fi

if [ ! -d "$TOOLCHAIN" ];then
    echo "Android toolchain not found in $TOOLCHAIN"
    exit 1
fi

if [ ! -d release ]
then
    mkdir release
fi

q=x
if [ "$#" -gt 0 ];
then
    q="$1"
else
    echo "Specify absolute path to Qt installation"
    read q
fi

cd release
cmake ../HuggleLite -DANDROID_STANDALONE_TOOLCHAIN=/opt/android-toolchain -DCMAKE_PREFIX_PATH="$q" -DCMAKE_TOOLCHAIN_FILE=../../deps/qt-android-cmake/toolchain/android.toolchain.cmake
